'''////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' Your custom recording code should go in this file.
' The designer will only add methods to this file, so your custom code won't be overwritten.
' http://www.ranorex.com
' 
'''////////////////////////////////////////////////////////////////////////////

Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports WinForms = System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Testing

Namespace DBConnectorExample
	Public Partial Class GetDataFromDBB
		''' <summary>
		''' This method gets called right after the recording has been started.
		''' It can be used to execute recording specific initialization code.
		''' </summary>
		Private Sub Init()
			' Your recording specific initialization code goes here.
		End Sub

		Public Sub compDataB2NDb()
			If varDBAR = varDBBR Then
				Report.Info("These case numbers match. ")
			Else
				Report.Info("These case numbers do not match. ")
			End If
		End Sub

	End Class
End Namespace
