'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports WinForms = System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Testing
Imports Ranorex.Core.Repository

Namespace DBConnectorExample
    ''' <summary>
    '''The GetDataFromDBB recording.
    ''' </summary>
    <TestModule("4c5516ee-16f6-44e6-8adf-796162040fc5", ModuleType.Recording, 1)> _
    Partial Public Class GetDataFromDBB
        Implements ITestModule

        ''' <summary>
        ''' Holds an instance of the DBConnectorExampleRepository repository.
        ''' </summary>
        Public Shared repo as DBConnectorExampleRepository = DBConnectorExampleRepository.Instance

        Shared _instance as GetDataFromDBB = new GetDataFromDBB()

        ''' <summary>
        ''' Constructs a new instance.
        ''' </summary>
        Sub New()
            varDBBR = "2"
            varDBAR = "1"
            varGBL = ""
        End Sub

        ''' <summary>
        ''' Gets a static instance of this recording.
        ''' </summary>
        Public Shared ReadOnly Property Instance As GetDataFromDBB
            Get
                Return _instance
            End Get
        End Property

#Region "Variables"

        Dim _varDBBR As String

        ''' <summary>
        ''' Gets or sets the value of variable varDBBR.
        ''' </summary>
        <TestVariable("b8e1a2c3-b113-472e-a911-f990f19a1a19")> _
        Public Property varDBBR As String
            Get
                Return _varDBBR
            End Get
            Set(ByVal value As String)
                _varDBBR = value
            End Set
        End Property

        Dim _varDBAR As String

        ''' <summary>
        ''' Gets or sets the value of variable varDBAR.
        ''' </summary>
        <TestVariable("63608d13-ef8c-47f0-aed8-a1b2c0566177")> _
        Public Property varDBAR As String
            Get
                Return _varDBAR
            End Get
            Set(ByVal value As String)
                _varDBAR = value
            End Set
        End Property

        Dim _varGBL As String

        ''' <summary>
        ''' Gets or sets the value of variable varGBL.
        ''' </summary>
        <TestVariable("0ca3fbec-0f6e-4d01-b382-35d849fc54fc")> _
        Public Property varGBL As String
            Get
                Return _varGBL
            End Get
            Set(ByVal value As String)
                _varGBL = value
            End Set
        End Property

#End Region

        ''' <summary>
        ''' Starts the replay of the static recording <see cref="Instance"/>.
        ''' </summary>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")> _
        Public Shared Sub Start()
            TestModuleRunner.Run(Instance)
        End Sub

        ''' <summary>
        ''' Performs the playback of actions in this recording.
        ''' </summary>
        ''' <remarks>You should not call this method directly, instead pass the module
        ''' instance to the <see cref="TestModuleRunner.Run(Of ITestModule)"/> method
        ''' that will in turn invoke this method.</remarks>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")> _
        Sub Run() Implements ITestModule.Run
            Mouse.DefaultMoveTime = 300
            Keyboard.DefaultKeyPressTime = 100
            Delay.SpeedFactor = 1.0

            Init()

            compDataB2NDb()
            Delay.Milliseconds(0)
            
        End Sub

#Region "Image Feature Data"
#End Region

    End Class

End Namespace
