'''////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' Your custom recording code should go in this file.
' The designer will only add methods to this file, so your custom code won't be overwritten.
' http://www.ranorex.com
' 
'''////////////////////////////////////////////////////////////////////////////

Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports WinForms = System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Testing
Imports System.Data
Imports System.Data.OleDb
'must have this as a using statement!!
Namespace DBConnectorExample
	Public Partial Class Recording1
		''' <summary>
		''' This method gets called right after the recording has been started.
		''' It can be used to execute recording specific initialization code.
		''' </summary>
		Private Sub Init()
			' Your recording specific initialization code goes here.
		End Sub



		'=========================================================================================================================
		' This function will not work without changing the connection string portion
		'=========================================================================================================================



		Public Sub compareDataFromDBA2B()
			'This has to be modified to the correct location of the DB's
			Dim con As New OleDbConnection("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\aahsan\Desktop\DBExample\DBConnectorExample\DatabaseA.accdb;")
			'This has to be modified to the correct location of the DB's
			Dim con2 As New OleDbConnection("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\aahsan\Desktop\DBExample\DBConnectorExample\DatabaseB.accdb;")

			Dim cmd As New OleDbCommand("select Casenumber From Table1", con)
			Dim cmd2 As New OleDbCommand("select Casenumber From Table1", con2)
			con.Open()
			con2.Open()
			Dim dr As OleDbDataReader = cmd.ExecuteReader()
			Dim dr2 As OleDbDataReader = cmd2.ExecuteReader()

			Dim row As Integer = 1
			While dr.Read()
				While dr2.Read()

					If dr("CaseNUmber").ToString() = dr2("CaseNUmber").ToString() Then
						Report.Info("Match Found at Row: " & row & "." & " The data in DB A " & (dr("CaseNUmber").ToString()) & " matches the data in DB B " & (dr2("CaseNUmber").ToString()))
						varRow1 = dr("CaseNUmber").ToString()
						TestCase.Current.Parameters("GBLRow1") = varRow1
					Else
						Report.Info("This data in DB A " & (dr("CaseNUmber").ToString()) & " doese not match the data in DB B " & (dr2("CaseNUmber").ToString()) & " in Row : " & row)
					End If
					row += 1
				End While
			End While
			con.Close()
			con2.Close()
		End Sub

	End Class
End Namespace
