'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports WinForms = System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Testing
Imports Ranorex.Core.Repository

Namespace DBConnectorExample
    ''' <summary>
    '''The Recording1 recording.
    ''' </summary>
    <TestModule("759d5cb4-b746-47b5-8c8e-b822e6c616f0", ModuleType.Recording, 1)> _
    Partial Public Class Recording1
        Implements ITestModule

        ''' <summary>
        ''' Holds an instance of the DBConnectorExampleRepository repository.
        ''' </summary>
        Public Shared repo as DBConnectorExampleRepository = DBConnectorExampleRepository.Instance

        Shared _instance as Recording1 = new Recording1()

        ''' <summary>
        ''' Constructs a new instance.
        ''' </summary>
        Sub New()
            varRow1 = ""
        End Sub

        ''' <summary>
        ''' Gets a static instance of this recording.
        ''' </summary>
        Public Shared ReadOnly Property Instance As Recording1
            Get
                Return _instance
            End Get
        End Property

#Region "Variables"

        Dim _varRow1 As String

        ''' <summary>
        ''' Gets or sets the value of variable varRow1.
        ''' </summary>
        <TestVariable("ed5f8680-4529-4605-9cd4-cb0f13ed3873")> _
        Public Property varRow1 As String
            Get
                Return _varRow1
            End Get
            Set(ByVal value As String)
                _varRow1 = value
            End Set
        End Property

#End Region

        ''' <summary>
        ''' Starts the replay of the static recording <see cref="Instance"/>.
        ''' </summary>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")> _
        Public Shared Sub Start()
            TestModuleRunner.Run(Instance)
        End Sub

        ''' <summary>
        ''' Performs the playback of actions in this recording.
        ''' </summary>
        ''' <remarks>You should not call this method directly, instead pass the module
        ''' instance to the <see cref="TestModuleRunner.Run(Of ITestModule)"/> method
        ''' that will in turn invoke this method.</remarks>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")> _
        Sub Run() Implements ITestModule.Run
            Mouse.DefaultMoveTime = 300
            Keyboard.DefaultKeyPressTime = 100
            Delay.SpeedFactor = 1.0

            Init()

            compareDataFromDBA2B()
            Delay.Milliseconds(0)
            
        End Sub

#Region "Image Feature Data"
#End Region

    End Class

End Namespace
