///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxMobileDemoInCode
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxMiniKeePassRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.3")]
    [RepositoryFolder("289cddcd-83dd-4739-ad51-0d209df62da3")]
    public partial class RxMiniKeePassRepo : RepoGenBaseFolder
    {
        static RxMiniKeePassRepo instance = new RxMiniKeePassRepo();
        RxMiniKeePassRepoFolders.RanorexMiniKeePassAppFolder _ranorexminikeepass;
        RepoItemInfo _btdone_rootlevelInfo;

        /// <summary>
        /// Gets the singleton class instance representing the RxMiniKeePassRepo element repository.
        /// </summary>
        [RepositoryFolder("289cddcd-83dd-4739-ad51-0d209df62da3")]
        public static RxMiniKeePassRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxMiniKeePassRepo() 
            : base("RxMiniKeePassRepo", "/", null, 0, false, "289cddcd-83dd-4739-ad51-0d209df62da3", ".\\RepositoryImages\\RxMiniKeePassRepo289cddcd.rximgres")
        {
            _ranorexminikeepass = new RxMiniKeePassRepoFolders.RanorexMiniKeePassAppFolder(this);
            _btdone_rootlevelInfo = new RepoItemInfo(this, "btDone_RootLevel", "/mobileapp[@title='ranorex.MiniKeePass']/form//titlebar/button[@localizationkey='Done']", 8000, null, "6557c575-1ae0-4bff-accc-a112096bd696");
        }

#region Variables

        string _varDatabaseName = "RanorexMiniKeePass";

        /// <summary>
        /// Gets or sets the value of variable varDatabaseName.
        /// </summary>
        [TestVariable("fbcdb331-2f58-4773-bb36-195c273edce7")]
        public string varDatabaseName
        {
            get { return _varDatabaseName; }
            set { _varDatabaseName = value; }
        }

        string _varIconIndex = "8";

        /// <summary>
        /// Gets or sets the value of variable varIconIndex.
        /// </summary>
        [TestVariable("17ce097e-f80a-48e6-919d-ad457afd0654")]
        public string varIconIndex
        {
            get { return _varIconIndex; }
            set { _varIconIndex = value; }
        }

        string _varTitle = "WordPressDemo";

        /// <summary>
        /// Gets or sets the value of variable varTitle.
        /// </summary>
        [TestVariable("3e292e0d-9ad3-476b-99f3-502d41bf5434")]
        public string varTitle
        {
            get { return _varTitle; }
            set { _varTitle = value; }
        }

        string _varGroupName = "Ranorex";

        /// <summary>
        /// Gets or sets the value of variable varGroupName.
        /// </summary>
        [TestVariable("26b0f9ff-7824-4595-8df2-b8a53261cff5")]
        public string varGroupName
        {
            get { return _varGroupName; }
            set { _varGroupName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("289cddcd-83dd-4739-ad51-0d209df62da3")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The btDone_RootLevel item.
        /// </summary>
        [RepositoryItem("6557c575-1ae0-4bff-accc-a112096bd696")]
        public virtual Ranorex.Button btDone_RootLevel
        {
            get
            {
                 return _btdone_rootlevelInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The btDone_RootLevel item info.
        /// </summary>
        [RepositoryItemInfo("6557c575-1ae0-4bff-accc-a112096bd696")]
        public virtual RepoItemInfo btDone_RootLevelInfo
        {
            get
            {
                return _btdone_rootlevelInfo;
            }
        }

        /// <summary>
        /// The RanorexMiniKeePass folder.
        /// </summary>
        [RepositoryFolder("7c239340-5eef-4e55-8880-bb18e9a64c82")]
        public virtual RxMiniKeePassRepoFolders.RanorexMiniKeePassAppFolder RanorexMiniKeePass
        {
            get { return _ranorexminikeepass; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.3")]
    public partial class RxMiniKeePassRepoFolders
    {
        /// <summary>
        /// The RanorexMiniKeePassAppFolder folder.
        /// </summary>
        [RepositoryFolder("7c239340-5eef-4e55-8880-bb18e9a64c82")]
        public partial class RanorexMiniKeePassAppFolder : RepoGenBaseFolder
        {
            RxMiniKeePassRepoFolders.ControllerWrapperTableFolder _controllerwrappertable;
            RxMiniKeePassRepoFolders.TitlebarButtonsFolder _titlebarbuttons;
            RxMiniKeePassRepoFolders.TableFolder _table;
            RxMiniKeePassRepoFolders.ControllerWrapperContainerFolder _controllerwrappercontainer;
            RxMiniKeePassRepoFolders.TitlebarFolder _titlebar;
            RepoItemInfo _someformInfo;
            RepoItemInfo _addnewInfo;
            RepoItemInfo _entryInfo;
            RepoItemInfo _bticonInfo;
            RepoItemInfo _rxkdbInfo;
            RepoItemInfo _datadriveniconInfo;
            RepoItemInfo _toolbarconfirmdeleteInfo;

            /// <summary>
            /// Creates a new RanorexMiniKeePass  folder.
            /// </summary>
            public RanorexMiniKeePassAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RanorexMiniKeePass", "/mobileapp[@title='ranorex.MiniKeePass']", parentFolder, 30000, null, false, "7c239340-5eef-4e55-8880-bb18e9a64c82", "")
            {
                _controllerwrappertable = new RxMiniKeePassRepoFolders.ControllerWrapperTableFolder(this);
                _titlebarbuttons = new RxMiniKeePassRepoFolders.TitlebarButtonsFolder(this);
                _table = new RxMiniKeePassRepoFolders.TableFolder(this);
                _controllerwrappercontainer = new RxMiniKeePassRepoFolders.ControllerWrapperContainerFolder(this);
                _titlebar = new RxMiniKeePassRepoFolders.TitlebarFolder(this);
                _someformInfo = new RepoItemInfo(this, "SomeForm", "form", 90000, null, "8334ae6e-1f05-47d2-9750-64e44ac65f87");
                _addnewInfo = new RepoItemInfo(this, "AddNew", "form/container/toolbar/button[3]", 30000, null, "b17fe3ca-1938-4a52-ba91-533db80ecb33");
                _entryInfo = new RepoItemInfo(this, "Entry", "form?/container/container//.[@localizationkey='Entry']", 30000, null, "2d9f3106-4c84-452f-911d-ae024cde34a5");
                _bticonInfo = new RepoItemInfo(this, "btIcon", "form//table//container[@localizationkey='Title']/?/button[@accessibilitylabel='1']", 30000, null, "7ae8ad84-bb70-4d9d-bea5-fc12d927d0fb");
                _rxkdbInfo = new RepoItemInfo(this, "RxKdb", "form//table[@accessibilitylabel='Empty list' or @platformclass='UITableView']/?/?/cell//text[@accessibilitylabel~$varDatabaseName]/..", 30000, null, "cebe4971-17fd-426e-95c2-058975452190");
                _datadriveniconInfo = new RepoItemInfo(this, "DataDrivenIcon", "form/container/container/iosscrollview/ioselement/picture[@accessibilitylabel=$variconindex]", 30000, null, "4280a578-f683-4588-8fc6-5125abbb44fb");
                _toolbarconfirmdeleteInfo = new RepoItemInfo(this, "ToolBarConfirmDelete", ".//toolbar/button[1]", 30000, null, "770980a6-866b-4200-9915-7080874acb61");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7c239340-5eef-4e55-8880-bb18e9a64c82")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7c239340-5eef-4e55-8880-bb18e9a64c82")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeForm item.
            /// </summary>
            [RepositoryItem("8334ae6e-1f05-47d2-9750-64e44ac65f87")]
            public virtual Ranorex.Form SomeForm
            {
                get
                {
                    return _someformInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The SomeForm item info.
            /// </summary>
            [RepositoryItemInfo("8334ae6e-1f05-47d2-9750-64e44ac65f87")]
            public virtual RepoItemInfo SomeFormInfo
            {
                get
                {
                    return _someformInfo;
                }
            }

            /// <summary>
            /// The AddNew item.
            /// </summary>
            [RepositoryItem("b17fe3ca-1938-4a52-ba91-533db80ecb33")]
            public virtual Ranorex.Button AddNew
            {
                get
                {
                    return _addnewInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddNew item info.
            /// </summary>
            [RepositoryItemInfo("b17fe3ca-1938-4a52-ba91-533db80ecb33")]
            public virtual RepoItemInfo AddNewInfo
            {
                get
                {
                    return _addnewInfo;
                }
            }

            /// <summary>
            /// The Entry item.
            /// </summary>
            [RepositoryItem("2d9f3106-4c84-452f-911d-ae024cde34a5")]
            public virtual Ranorex.Unknown Entry
            {
                get
                {
                    return _entryInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Entry item info.
            /// </summary>
            [RepositoryItemInfo("2d9f3106-4c84-452f-911d-ae024cde34a5")]
            public virtual RepoItemInfo EntryInfo
            {
                get
                {
                    return _entryInfo;
                }
            }

            /// <summary>
            /// The btIcon item.
            /// </summary>
            [RepositoryItem("7ae8ad84-bb70-4d9d-bea5-fc12d927d0fb")]
            public virtual Ranorex.Button btIcon
            {
                get
                {
                    return _bticonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btIcon item info.
            /// </summary>
            [RepositoryItemInfo("7ae8ad84-bb70-4d9d-bea5-fc12d927d0fb")]
            public virtual RepoItemInfo btIconInfo
            {
                get
                {
                    return _bticonInfo;
                }
            }

            /// <summary>
            /// The RxKdb item.
            /// </summary>
            [RepositoryItem("cebe4971-17fd-426e-95c2-058975452190")]
            public virtual Ranorex.Unknown RxKdb
            {
                get
                {
                    return _rxkdbInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The RxKdb item info.
            /// </summary>
            [RepositoryItemInfo("cebe4971-17fd-426e-95c2-058975452190")]
            public virtual RepoItemInfo RxKdbInfo
            {
                get
                {
                    return _rxkdbInfo;
                }
            }

            /// <summary>
            /// The DataDrivenIcon item.
            /// </summary>
            [RepositoryItem("4280a578-f683-4588-8fc6-5125abbb44fb")]
            public virtual Ranorex.Picture DataDrivenIcon
            {
                get
                {
                    return _datadriveniconInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The DataDrivenIcon item info.
            /// </summary>
            [RepositoryItemInfo("4280a578-f683-4588-8fc6-5125abbb44fb")]
            public virtual RepoItemInfo DataDrivenIconInfo
            {
                get
                {
                    return _datadriveniconInfo;
                }
            }

            /// <summary>
            /// The ToolBarConfirmDelete item.
            /// </summary>
            [RepositoryItem("770980a6-866b-4200-9915-7080874acb61")]
            public virtual Ranorex.Button ToolBarConfirmDelete
            {
                get
                {
                    return _toolbarconfirmdeleteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ToolBarConfirmDelete item info.
            /// </summary>
            [RepositoryItemInfo("770980a6-866b-4200-9915-7080874acb61")]
            public virtual RepoItemInfo ToolBarConfirmDeleteInfo
            {
                get
                {
                    return _toolbarconfirmdeleteInfo;
                }
            }

            /// <summary>
            /// The ControllerWrapperTable folder.
            /// </summary>
            [RepositoryFolder("2989084a-da08-4d45-8e35-7bdc2a781d9e")]
            public virtual RxMiniKeePassRepoFolders.ControllerWrapperTableFolder ControllerWrapperTable
            {
                get { return _controllerwrappertable; }
            }

            /// <summary>
            /// The TitlebarButtons folder.
            /// </summary>
            [RepositoryFolder("b6335c31-1416-44ad-b102-b3cd3552ab62")]
            public virtual RxMiniKeePassRepoFolders.TitlebarButtonsFolder TitlebarButtons
            {
                get { return _titlebarbuttons; }
            }

            /// <summary>
            /// The Table folder.
            /// </summary>
            [RepositoryFolder("ac629da6-0c98-4f4e-92d8-8a3b49beec55")]
            public virtual RxMiniKeePassRepoFolders.TableFolder Table
            {
                get { return _table; }
            }

            /// <summary>
            /// The ControllerWrapperContainer folder.
            /// </summary>
            [RepositoryFolder("bcbec03c-5242-4d59-9772-b09dca627d04")]
            public virtual RxMiniKeePassRepoFolders.ControllerWrapperContainerFolder ControllerWrapperContainer
            {
                get { return _controllerwrappercontainer; }
            }

            /// <summary>
            /// The Titlebar folder.
            /// </summary>
            [RepositoryFolder("7ce581b1-6dae-4ab8-8aa3-81b7a76227c2")]
            public virtual RxMiniKeePassRepoFolders.TitlebarFolder Titlebar
            {
                get { return _titlebar; }
            }
        }

        /// <summary>
        /// The ControllerWrapperTableFolder folder.
        /// </summary>
        [RepositoryFolder("2989084a-da08-4d45-8e35-7bdc2a781d9e")]
        public partial class ControllerWrapperTableFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btdeleteInfo;
            RepoItemInfo _category_generalInfo;
            RepoItemInfo _category_internetInfo;
            RepoItemInfo _sometextInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _titleInfo;
            RepoItemInfo _urlInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _text_titleInfo;
            RepoItemInfo _newgroupInfo;
            RepoItemInfo _newgrouptextInfo;

            /// <summary>
            /// Creates a new ControllerWrapperTable  folder.
            /// </summary>
            public ControllerWrapperTableFolder(RepoGenBaseFolder parentFolder) :
                    base("ControllerWrapperTable", "form//table[@accessibilitylabel='Empty list' or @platformclass='UITableView']", parentFolder, 30000, null, false, "2989084a-da08-4d45-8e35-7bdc2a781d9e", "")
            {
                _btdeleteInfo = new RepoItemInfo(this, "btDelete", ".//cell[@accessibilitylabel~$vartitle]/../button", 30000, null, "9e0e0acf-6c06-4822-b441-cededcd36282");
                _category_generalInfo = new RepoItemInfo(this, "Category_General", ".//cell[@accessibilitylabel~'General']", 30000, null, "73c4e3ce-5171-4c28-9059-8f8aaf4ce24b");
                _category_internetInfo = new RepoItemInfo(this, "Category_Internet", ".//cell[@accessibilitylabel~'Internet']", 30000, null, "8aadfcc3-83cc-4bf6-831d-81fc18399566");
                _sometextInfo = new RepoItemInfo(this, "SomeText", ".//container[@platformclass='MasterPasswordFieldCell']//cell/?/?//text[@visible='True']", 30000, null, "b5245eb9-6526-4cba-9f5e-21aeeeee1eb2");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//container[@localizationkey='Password']/?//text[@localizationkey=null()]", 30000, null, "531255e6-6a80-4f5c-92d7-b10d5a5e6fb0");
                _titleInfo = new RepoItemInfo(this, "Title", ".//container[@localizationkey='Title']/?//text[@localizationkey='New Entry']", 30000, null, "f1229ae0-91fc-4fcd-9d1b-b610b392210b");
                _urlInfo = new RepoItemInfo(this, "URL", ".//container[@localizationkey='URL']/?//text[@localizationkey=null()]", 30000, null, "f2b5d286-04d3-49bd-8729-96164bbab3b4");
                _usernameInfo = new RepoItemInfo(this, "Username", ".//container[@localizationkey='Username']/?//text[@localizationkey=null()]", 30000, null, "3066c934-39f0-4495-b47d-dcf83370e006");
                _text_titleInfo = new RepoItemInfo(this, "Text_Title", ".//cell/text[@accessibilitylabel=$vartitle]", 30000, null, "76678876-a11b-48bd-9677-9adcfb57a36b");
                _newgroupInfo = new RepoItemInfo(this, "NewGroup", ".//cell/text[@accessibilitylabel=$vargroupname]", 30000, null, "0be1f6a7-914a-4a2b-bd02-06930c5da9bb");
                _newgrouptextInfo = new RepoItemInfo(this, "NewGroupText", ".//cell//text[@localizationkey='New Group']", 30000, null, "cab26c7d-ef48-4dfe-8ae0-aa0cfb4fcaf8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2989084a-da08-4d45-8e35-7bdc2a781d9e")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2989084a-da08-4d45-8e35-7bdc2a781d9e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btDelete item.
            /// </summary>
            [RepositoryItem("9e0e0acf-6c06-4822-b441-cededcd36282")]
            public virtual Ranorex.Button btDelete
            {
                get
                {
                    return _btdeleteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btDelete item info.
            /// </summary>
            [RepositoryItemInfo("9e0e0acf-6c06-4822-b441-cededcd36282")]
            public virtual RepoItemInfo btDeleteInfo
            {
                get
                {
                    return _btdeleteInfo;
                }
            }

            /// <summary>
            /// The Category_General item.
            /// </summary>
            [RepositoryItem("73c4e3ce-5171-4c28-9059-8f8aaf4ce24b")]
            public virtual Ranorex.Cell Category_General
            {
                get
                {
                    return _category_generalInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Category_General item info.
            /// </summary>
            [RepositoryItemInfo("73c4e3ce-5171-4c28-9059-8f8aaf4ce24b")]
            public virtual RepoItemInfo Category_GeneralInfo
            {
                get
                {
                    return _category_generalInfo;
                }
            }

            /// <summary>
            /// The Category_Internet item.
            /// </summary>
            [RepositoryItem("8aadfcc3-83cc-4bf6-831d-81fc18399566")]
            public virtual Ranorex.Cell Category_Internet
            {
                get
                {
                    return _category_internetInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Category_Internet item info.
            /// </summary>
            [RepositoryItemInfo("8aadfcc3-83cc-4bf6-831d-81fc18399566")]
            public virtual RepoItemInfo Category_InternetInfo
            {
                get
                {
                    return _category_internetInfo;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("b5245eb9-6526-4cba-9f5e-21aeeeee1eb2")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("b5245eb9-6526-4cba-9f5e-21aeeeee1eb2")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("531255e6-6a80-4f5c-92d7-b10d5a5e6fb0")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("531255e6-6a80-4f5c-92d7-b10d5a5e6fb0")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Title item.
            /// </summary>
            [RepositoryItem("f1229ae0-91fc-4fcd-9d1b-b610b392210b")]
            public virtual Ranorex.Text Title
            {
                get
                {
                    return _titleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Title item info.
            /// </summary>
            [RepositoryItemInfo("f1229ae0-91fc-4fcd-9d1b-b610b392210b")]
            public virtual RepoItemInfo TitleInfo
            {
                get
                {
                    return _titleInfo;
                }
            }

            /// <summary>
            /// The URL item.
            /// </summary>
            [RepositoryItem("f2b5d286-04d3-49bd-8729-96164bbab3b4")]
            public virtual Ranorex.Text URL
            {
                get
                {
                    return _urlInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The URL item info.
            /// </summary>
            [RepositoryItemInfo("f2b5d286-04d3-49bd-8729-96164bbab3b4")]
            public virtual RepoItemInfo URLInfo
            {
                get
                {
                    return _urlInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("3066c934-39f0-4495-b47d-dcf83370e006")]
            public virtual Ranorex.Text Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("3066c934-39f0-4495-b47d-dcf83370e006")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Text_Title item.
            /// </summary>
            [RepositoryItem("76678876-a11b-48bd-9677-9adcfb57a36b")]
            public virtual Ranorex.Text Text_Title
            {
                get
                {
                    return _text_titleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text_Title item info.
            /// </summary>
            [RepositoryItemInfo("76678876-a11b-48bd-9677-9adcfb57a36b")]
            public virtual RepoItemInfo Text_TitleInfo
            {
                get
                {
                    return _text_titleInfo;
                }
            }

            /// <summary>
            /// The NewGroup item.
            /// </summary>
            [RepositoryItem("0be1f6a7-914a-4a2b-bd02-06930c5da9bb")]
            public virtual Ranorex.Text NewGroup
            {
                get
                {
                    return _newgroupInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NewGroup item info.
            /// </summary>
            [RepositoryItemInfo("0be1f6a7-914a-4a2b-bd02-06930c5da9bb")]
            public virtual RepoItemInfo NewGroupInfo
            {
                get
                {
                    return _newgroupInfo;
                }
            }

            /// <summary>
            /// The NewGroupText item.
            /// </summary>
            [RepositoryItem("cab26c7d-ef48-4dfe-8ae0-aa0cfb4fcaf8")]
            public virtual Ranorex.Text NewGroupText
            {
                get
                {
                    return _newgrouptextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NewGroupText item info.
            /// </summary>
            [RepositoryItemInfo("cab26c7d-ef48-4dfe-8ae0-aa0cfb4fcaf8")]
            public virtual RepoItemInfo NewGroupTextInfo
            {
                get
                {
                    return _newgrouptextInfo;
                }
            }
        }

        /// <summary>
        /// The TitlebarButtonsFolder folder.
        /// </summary>
        [RepositoryFolder("b6335c31-1416-44ad-b102-b3cd3552ab62")]
        public partial class TitlebarButtonsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _internetInfo;
            RepoItemInfo _editInfo;
            RepoItemInfo _doneInfo;
            RepoItemInfo _generalInfo;
            RepoItemInfo _ranorexkeepassInfo;
            RepoItemInfo _filesInfo;
            RepoItemInfo _titlebarentryInfo;

            /// <summary>
            /// Creates a new TitlebarButtons  folder.
            /// </summary>
            public TitlebarButtonsFolder(RepoGenBaseFolder parentFolder) :
                    base("TitlebarButtons", "form//titlebar", parentFolder, 30000, null, false, "b6335c31-1416-44ad-b102-b3cd3552ab62", "")
            {
                _internetInfo = new RepoItemInfo(this, "Internet", "button[@accessibilitylabel='Internet']", 30000, null, "f9aa484b-b3aa-42b3-bb22-31fd401771df");
                _editInfo = new RepoItemInfo(this, "Edit", "button[@localizationkey='Edit']", 30000, null, "acb2be97-4c8b-417b-acee-b4f18adeede7");
                _doneInfo = new RepoItemInfo(this, "Done", "button[@localizationkey='Done']", 5000, null, "22e22960-4edd-4278-968b-fa7bd10de6b0");
                _generalInfo = new RepoItemInfo(this, "General", "button[@accessibilitylabel='General']", 30000, null, "79d7c8b5-5d32-4330-a3a2-09d92027ce29");
                _ranorexkeepassInfo = new RepoItemInfo(this, "RanorexKeePass", "button[@accessibilitylabel=$vardatabasename or @accessibilitylabel='Back']", 30000, null, "5d1f6231-bef3-492d-a9e9-7385cdd13d2e");
                _filesInfo = new RepoItemInfo(this, "Files", "button[@localizationkey='Files']", 30000, null, "40c19870-53ee-4979-b5ac-e5390c3a5b00");
                _titlebarentryInfo = new RepoItemInfo(this, "TitleBarEntry", "button", 30000, null, "f1924e05-d3b6-4c36-a4d2-2e7bb7278955");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b6335c31-1416-44ad-b102-b3cd3552ab62")]
            public virtual Ranorex.TitleBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b6335c31-1416-44ad-b102-b3cd3552ab62")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Internet item.
            /// </summary>
            [RepositoryItem("f9aa484b-b3aa-42b3-bb22-31fd401771df")]
            public virtual Ranorex.Button Internet
            {
                get
                {
                    return _internetInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Internet item info.
            /// </summary>
            [RepositoryItemInfo("f9aa484b-b3aa-42b3-bb22-31fd401771df")]
            public virtual RepoItemInfo InternetInfo
            {
                get
                {
                    return _internetInfo;
                }
            }

            /// <summary>
            /// The Edit item.
            /// </summary>
            [RepositoryItem("acb2be97-4c8b-417b-acee-b4f18adeede7")]
            public virtual Ranorex.Button Edit
            {
                get
                {
                    return _editInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Edit item info.
            /// </summary>
            [RepositoryItemInfo("acb2be97-4c8b-417b-acee-b4f18adeede7")]
            public virtual RepoItemInfo EditInfo
            {
                get
                {
                    return _editInfo;
                }
            }

            /// <summary>
            /// The Done item.
            /// </summary>
            [RepositoryItem("22e22960-4edd-4278-968b-fa7bd10de6b0")]
            public virtual Ranorex.Button Done
            {
                get
                {
                    return _doneInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Done item info.
            /// </summary>
            [RepositoryItemInfo("22e22960-4edd-4278-968b-fa7bd10de6b0")]
            public virtual RepoItemInfo DoneInfo
            {
                get
                {
                    return _doneInfo;
                }
            }

            /// <summary>
            /// The General item.
            /// </summary>
            [RepositoryItem("79d7c8b5-5d32-4330-a3a2-09d92027ce29")]
            public virtual Ranorex.Button General
            {
                get
                {
                    return _generalInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The General item info.
            /// </summary>
            [RepositoryItemInfo("79d7c8b5-5d32-4330-a3a2-09d92027ce29")]
            public virtual RepoItemInfo GeneralInfo
            {
                get
                {
                    return _generalInfo;
                }
            }

            /// <summary>
            /// The RanorexKeePass item.
            /// </summary>
            [RepositoryItem("5d1f6231-bef3-492d-a9e9-7385cdd13d2e")]
            public virtual Ranorex.Button RanorexKeePass
            {
                get
                {
                    return _ranorexkeepassInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RanorexKeePass item info.
            /// </summary>
            [RepositoryItemInfo("5d1f6231-bef3-492d-a9e9-7385cdd13d2e")]
            public virtual RepoItemInfo RanorexKeePassInfo
            {
                get
                {
                    return _ranorexkeepassInfo;
                }
            }

            /// <summary>
            /// The Files item.
            /// </summary>
            [RepositoryItem("40c19870-53ee-4979-b5ac-e5390c3a5b00")]
            public virtual Ranorex.Button Files
            {
                get
                {
                    return _filesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Files item info.
            /// </summary>
            [RepositoryItemInfo("40c19870-53ee-4979-b5ac-e5390c3a5b00")]
            public virtual RepoItemInfo FilesInfo
            {
                get
                {
                    return _filesInfo;
                }
            }

            /// <summary>
            /// The TitleBarEntry item.
            /// </summary>
            [RepositoryItem("f1924e05-d3b6-4c36-a4d2-2e7bb7278955")]
            public virtual Ranorex.Button TitleBarEntry
            {
                get
                {
                    return _titlebarentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The TitleBarEntry item info.
            /// </summary>
            [RepositoryItemInfo("f1924e05-d3b6-4c36-a4d2-2e7bb7278955")]
            public virtual RepoItemInfo TitleBarEntryInfo
            {
                get
                {
                    return _titlebarentryInfo;
                }
            }
        }

        /// <summary>
        /// The TableFolder folder.
        /// </summary>
        [RepositoryFolder("ac629da6-0c98-4f4e-92d8-8a3b49beec55")]
        public partial class TableFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textdatabasenameInfo;
            RepoItemInfo _textpasswordInfo;
            RepoItemInfo _textconfirmpasswordInfo;
            RepoItemInfo _deleteInfo;
            RepoItemInfo _delete1Info;

            /// <summary>
            /// Creates a new Table  folder.
            /// </summary>
            public TableFolder(RepoGenBaseFolder parentFolder) :
                    base("Table", "form//table[@accessibilitylabel='Empty list' or @platformclass='UITableView']", parentFolder, 30000, null, false, "ac629da6-0c98-4f4e-92d8-8a3b49beec55", "")
            {
                _textdatabasenameInfo = new RepoItemInfo(this, "TextDatabaseName", "container?/cell[1]/container?/text", 30000, null, "2c24014d-c47a-4835-9562-af90d24bf0e2");
                _textpasswordInfo = new RepoItemInfo(this, "TextPassword", "container?/cell[2]/container?/text", 30000, null, "aeec98c4-43a0-4861-a4fe-2f40e157c7f3");
                _textconfirmpasswordInfo = new RepoItemInfo(this, "TextConfirmPassword", "container?/cell[3]/container?/text", 30000, null, "33e5faa0-5abb-47cd-be6a-938c2be3c91c");
                _deleteInfo = new RepoItemInfo(this, "Delete", ".//cell/text[@accessibilitylabel~$vardatabasename]/../../button", 30000, null, "a2613ccb-c798-4dbb-89ec-d524d681e2eb");
                _delete1Info = new RepoItemInfo(this, "Delete1", ".//container[@platformclass='UITableViewCellDeleteConfirmationView']//button", 30000, null, "6adaa2d3-ead1-4a35-b64b-2c0327f855cc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ac629da6-0c98-4f4e-92d8-8a3b49beec55")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ac629da6-0c98-4f4e-92d8-8a3b49beec55")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TextDatabaseName item.
            /// </summary>
            [RepositoryItem("2c24014d-c47a-4835-9562-af90d24bf0e2")]
            public virtual Ranorex.Text TextDatabaseName
            {
                get
                {
                    return _textdatabasenameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextDatabaseName item info.
            /// </summary>
            [RepositoryItemInfo("2c24014d-c47a-4835-9562-af90d24bf0e2")]
            public virtual RepoItemInfo TextDatabaseNameInfo
            {
                get
                {
                    return _textdatabasenameInfo;
                }
            }

            /// <summary>
            /// The TextPassword item.
            /// </summary>
            [RepositoryItem("aeec98c4-43a0-4861-a4fe-2f40e157c7f3")]
            public virtual Ranorex.Text TextPassword
            {
                get
                {
                    return _textpasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextPassword item info.
            /// </summary>
            [RepositoryItemInfo("aeec98c4-43a0-4861-a4fe-2f40e157c7f3")]
            public virtual RepoItemInfo TextPasswordInfo
            {
                get
                {
                    return _textpasswordInfo;
                }
            }

            /// <summary>
            /// The TextConfirmPassword item.
            /// </summary>
            [RepositoryItem("33e5faa0-5abb-47cd-be6a-938c2be3c91c")]
            public virtual Ranorex.Text TextConfirmPassword
            {
                get
                {
                    return _textconfirmpasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextConfirmPassword item info.
            /// </summary>
            [RepositoryItemInfo("33e5faa0-5abb-47cd-be6a-938c2be3c91c")]
            public virtual RepoItemInfo TextConfirmPasswordInfo
            {
                get
                {
                    return _textconfirmpasswordInfo;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("a2613ccb-c798-4dbb-89ec-d524d681e2eb")]
            public virtual Ranorex.Button Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("a2613ccb-c798-4dbb-89ec-d524d681e2eb")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }

            /// <summary>
            /// The Delete1 item.
            /// </summary>
            [RepositoryItem("6adaa2d3-ead1-4a35-b64b-2c0327f855cc")]
            public virtual Ranorex.Button Delete1
            {
                get
                {
                    return _delete1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Delete1 item info.
            /// </summary>
            [RepositoryItemInfo("6adaa2d3-ead1-4a35-b64b-2c0327f855cc")]
            public virtual RepoItemInfo Delete1Info
            {
                get
                {
                    return _delete1Info;
                }
            }
        }

        /// <summary>
        /// The ControllerWrapperContainerFolder folder.
        /// </summary>
        [RepositoryFolder("bcbec03c-5242-4d59-9772-b09dca627d04")]
        public partial class ControllerWrapperContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _groupiconInfo;
            RepoItemInfo _delete_categoryInfo;
            RepoItemInfo _buttoniconInfo;

            /// <summary>
            /// Creates a new ControllerWrapperContainer  folder.
            /// </summary>
            public ControllerWrapperContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("ControllerWrapperContainer", "form/?/?", parentFolder, 30000, null, false, "bcbec03c-5242-4d59-9772-b09dca627d04", "")
            {
                _groupiconInfo = new RepoItemInfo(this, "GroupIcon", "iosscrollview/ioselement/picture[@accessibilitylabel='53']", 30000, null, "ccc432fe-b576-4c79-bac8-9d887fcfc02f");
                _delete_categoryInfo = new RepoItemInfo(this, "Delete_Category", "table//cell/text[@accessibilitylabel=$vargroupname]/../../button", 30000, null, "381e3f31-be33-4036-87c8-5c05286d7492");
                _buttoniconInfo = new RepoItemInfo(this, "ButtonIcon", "table[@accessibilitylabel='Empty list' or @platformclass='UITableView']/?/container[@localizationkey='Image']//button[@accessibilitylabel='48']", 30000, null, "8b3d3b90-f9f6-415a-a77a-b3f7f87d5872");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bcbec03c-5242-4d59-9772-b09dca627d04")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bcbec03c-5242-4d59-9772-b09dca627d04")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GroupIcon item.
            /// </summary>
            [RepositoryItem("ccc432fe-b576-4c79-bac8-9d887fcfc02f")]
            public virtual Ranorex.Picture GroupIcon
            {
                get
                {
                    return _groupiconInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The GroupIcon item info.
            /// </summary>
            [RepositoryItemInfo("ccc432fe-b576-4c79-bac8-9d887fcfc02f")]
            public virtual RepoItemInfo GroupIconInfo
            {
                get
                {
                    return _groupiconInfo;
                }
            }

            /// <summary>
            /// The Delete_Category item.
            /// </summary>
            [RepositoryItem("381e3f31-be33-4036-87c8-5c05286d7492")]
            public virtual Ranorex.Button Delete_Category
            {
                get
                {
                    return _delete_categoryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Delete_Category item info.
            /// </summary>
            [RepositoryItemInfo("381e3f31-be33-4036-87c8-5c05286d7492")]
            public virtual RepoItemInfo Delete_CategoryInfo
            {
                get
                {
                    return _delete_categoryInfo;
                }
            }

            /// <summary>
            /// The ButtonIcon item.
            /// </summary>
            [RepositoryItem("8b3d3b90-f9f6-415a-a77a-b3f7f87d5872")]
            public virtual Ranorex.Button ButtonIcon
            {
                get
                {
                    return _buttoniconInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonIcon item info.
            /// </summary>
            [RepositoryItemInfo("8b3d3b90-f9f6-415a-a77a-b3f7f87d5872")]
            public virtual RepoItemInfo ButtonIconInfo
            {
                get
                {
                    return _buttoniconInfo;
                }
            }
        }

        /// <summary>
        /// The TitlebarFolder folder.
        /// </summary>
        [RepositoryFolder("7ce581b1-6dae-4ab8-8aa3-81b7a76227c2")]
        public partial class TitlebarFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btdatabaseInfo;
            RepoItemInfo _editgroupInfo;
            RepoItemInfo _groupInfo;

            /// <summary>
            /// Creates a new Titlebar  folder.
            /// </summary>
            public TitlebarFolder(RepoGenBaseFolder parentFolder) :
                    base("Titlebar", "form?/container", parentFolder, 30000, null, false, "7ce581b1-6dae-4ab8-8aa3-81b7a76227c2", "")
            {
                _btdatabaseInfo = new RepoItemInfo(this, "btDatabase", "titlebar/button[@accessibilitylabel=$vardatabasename or @accessibilitylabel='Back']", 30000, null, "905a8369-128e-4632-82df-74c27178a354");
                _editgroupInfo = new RepoItemInfo(this, "EditGroup", "titlebar/button[@localizationkey='Edit Group']", 30000, null, "01ca9807-880c-48aa-82ad-bfcc55433f34");
                _groupInfo = new RepoItemInfo(this, "Group", "container//.[@localizationkey='Group']", 30000, null, "48956953-9145-4d80-9924-d5cab3caa62e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7ce581b1-6dae-4ab8-8aa3-81b7a76227c2")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ce581b1-6dae-4ab8-8aa3-81b7a76227c2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btDatabase item.
            /// </summary>
            [RepositoryItem("905a8369-128e-4632-82df-74c27178a354")]
            public virtual Ranorex.Button btDatabase
            {
                get
                {
                    return _btdatabaseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btDatabase item info.
            /// </summary>
            [RepositoryItemInfo("905a8369-128e-4632-82df-74c27178a354")]
            public virtual RepoItemInfo btDatabaseInfo
            {
                get
                {
                    return _btdatabaseInfo;
                }
            }

            /// <summary>
            /// The EditGroup item.
            /// </summary>
            [RepositoryItem("01ca9807-880c-48aa-82ad-bfcc55433f34")]
            public virtual Ranorex.Button EditGroup
            {
                get
                {
                    return _editgroupInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EditGroup item info.
            /// </summary>
            [RepositoryItemInfo("01ca9807-880c-48aa-82ad-bfcc55433f34")]
            public virtual RepoItemInfo EditGroupInfo
            {
                get
                {
                    return _editgroupInfo;
                }
            }

            /// <summary>
            /// The Group item.
            /// </summary>
            [RepositoryItem("48956953-9145-4d80-9924-d5cab3caa62e")]
            public virtual Ranorex.Unknown Group
            {
                get
                {
                    return _groupInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Group item info.
            /// </summary>
            [RepositoryItemInfo("48956953-9145-4d80-9924-d5cab3caa62e")]
            public virtual RepoItemInfo GroupInfo
            {
                get
                {
                    return _groupInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}