///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxMobileDemoInCode
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxMobileDemoInCodeRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.3")]
    [RepositoryFolder("a9244780-65cf-4971-a132-057eebedf710")]
    public partial class RxMobileDemoInCodeRepository : RepoGenBaseFolder
    {
        static RxMobileDemoInCodeRepository instance = new RxMobileDemoInCodeRepository();

        /// <summary>
        /// Gets the singleton class instance representing the RxMobileDemoInCodeRepository element repository.
        /// </summary>
        [RepositoryFolder("a9244780-65cf-4971-a132-057eebedf710")]
        public static RxMobileDemoInCodeRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxMobileDemoInCodeRepository() 
            : base("RxMobileDemoInCodeRepository", "/", null, 0, false, "a9244780-65cf-4971-a132-057eebedf710", ".\\RepositoryImages\\RxMobileDemoInCodeRepositorya9244780.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a9244780-65cf-4971-a132-057eebedf710")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.3")]
    public partial class RxMobileDemoInCodeRepositoryFolders
    {
    }
#pragma warning restore 0436
}