///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PerformanceTest_WriteToDB
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PerformanceTest_WriteToDBRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
    [RepositoryFolder("bd1346f1-943e-4d26-99ae-ee62f09aa83b")]
    public partial class PerformanceTest_WriteToDBRepository : RepoGenBaseFolder
    {
        static PerformanceTest_WriteToDBRepository instance = new PerformanceTest_WriteToDBRepository();

        /// <summary>
        /// Gets the singleton class instance representing the PerformanceTest_WriteToDBRepository element repository.
        /// </summary>
        [RepositoryFolder("bd1346f1-943e-4d26-99ae-ee62f09aa83b")]
        public static PerformanceTest_WriteToDBRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PerformanceTest_WriteToDBRepository() 
            : base("PerformanceTest_WriteToDBRepository", "/", null, 0, false, "bd1346f1-943e-4d26-99ae-ee62f09aa83b", ".\\RepositoryImages\\PerformanceTest_WriteToDBRepositorybd1346f1.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("bd1346f1-943e-4d26-99ae-ee62f09aa83b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
    public partial class PerformanceTest_WriteToDBRepositoryFolders
    {
    }
#pragma warning restore 0436
}