///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using System.Data;
using System.Data.OleDb; //must have this as a using statement!!

namespace DBConnectorExample
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        
        
        //=========================================================================================================================
        // This function will not work without changing the connection string portion
        //=========================================================================================================================

        
        
        public void compareDataFromDBA2B(Ranorex.Adapter argument1, string argument2)
        {
        	//This has to be modified to the correct location of the DB's
        	OleDbConnection con =
         		new OleDbConnection(@"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\aahsan\Desktop\DBExample\DBConnectorExample\DatabaseA.accdb;");
            //This has to be modified to the correct location of the DB's
        	OleDbConnection con2 =
            	new OleDbConnection(@"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\aahsan\Desktop\DBExample\DBConnectorExample\DatabaseB.accdb;");
            
            OleDbCommand cmd = new OleDbCommand("select Casenumber From Table1", con);
            OleDbCommand cmd2 = new OleDbCommand("select Casenumber From Table1", con2);
            con.Open();
            con2.Open();
            OleDbDataReader dr = cmd.ExecuteReader();
            OleDbDataReader dr2 = cmd2.ExecuteReader();

            int row = 1;
            while(dr.Read()){
            	while(dr2.Read()){
	           
	          		if (dr["CaseNUmber"].ToString() == dr2["CaseNUmber"].ToString())
	            	{
	           			Report.Info("Match Found at Row: " + row + "." +" The data in DB A " + (dr["CaseNUmber"].ToString()) + " matches the data in DB B " + (dr2["CaseNUmber"].ToString()));
	           			varRow1 = dr["CaseNUmber"].ToString();
	           			TestCase.Current.Parameters["GBLRow1"] = varRow1;
	           		}
	          		else
	          		{
	          			Report.Info("This data in DB A " + (dr["CaseNUmber"].ToString()) + " doese not match the data in DB B " + (dr2["CaseNUmber"].ToString()) + " in Row : " + row);
	          		}
	          	row++;
            	}
			}
			con.Close();
			con2.Close();   
        }

    }
}