///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DBConnectorExample
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("759d5cb4-b746-47b5-8c8e-b822e6c616f0", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DBConnectorExampleRepository repository.
        /// </summary>
        public static DBConnectorExampleRepository repo = DBConnectorExampleRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
            varRow1 = "";
            SnapShotLocation = "C:\\Users\\aahsan\\Desktop\\DBExample\\DBConnectorExample\\TableSnapshot.rxsnp";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _varRow1;

        /// <summary>
        /// Gets or sets the value of variable varRow1.
        /// </summary>
        [TestVariable("ed5f8680-4529-4605-9cd4-cb0f13ed3873")]
        public string varRow1
        {
            get { return _varRow1; }
            set { _varRow1 = value; }
        }

        string _SnapShotLocation;

        /// <summary>
        /// Gets or sets the value of variable SnapShotLocation.
        /// </summary>
        [TestVariable("c6e77b26-8ac1-4f71-b0f3-307f52b9cb6f")]
        public string SnapShotLocation
        {
            get { return _SnapShotLocation; }
            set { _SnapShotLocation = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'C:\\Users\\aahsan\\Desktop\\DBExample\\DBConnectorExample\\HTMLTable.html' with browser 'IE' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("C:\\Users\\aahsan\\Desktop\\DBExample\\DBConnectorExample\\HTMLTable.html", "IE", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            compareDataFromDBA2B(repo.HTMLTableHtml.SomeTableTag, SnapShotLocation);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
